// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEVRYy0ZWxHES7MrhtU3h4yIT5XYmSkbo',
    appId: '1:839859985694:web:52520ef5b0031f89adbd0f',
    messagingSenderId: '839859985694',
    projectId: 'yudis-project1',
    authDomain: 'yudis-project1.firebaseapp.com',
    storageBucket: 'yudis-project1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZCbyK_ATaIM_ZlIegrAy_8QnMovsUmXY',
    appId: '1:839859985694:android:36f1c05081bcc680adbd0f',
    messagingSenderId: '839859985694',
    projectId: 'yudis-project1',
    storageBucket: 'yudis-project1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBL5E95JQuSzcdQY-ANwNIXgz8aXkKvU',
    appId: '1:839859985694:ios:84632436a4f72616adbd0f',
    messagingSenderId: '839859985694',
    projectId: 'yudis-project1',
    storageBucket: 'yudis-project1.appspot.com',
    iosBundleId: 'com.example.landingPage3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMBL5E95JQuSzcdQY-ANwNIXgz8aXkKvU',
    appId: '1:839859985694:ios:28f01b98302fca78adbd0f',
    messagingSenderId: '839859985694',
    projectId: 'yudis-project1',
    storageBucket: 'yudis-project1.appspot.com',
    iosBundleId: 'com.example.landingPage3.RunnerTests',
  );
}
